---
editor: code
repo_path: ~/problems
navigator_url: "https://navigator.wethinkcode.co.za"
username: yzwane@student.wethinkcode.co.za
review_manager_url: "https://review-manager.wethinkcode.co.za"
keycloak_url: "https://keycloak.wethinkcode.co.za"