#!bin/bash
echo "Enter a base folder name"
read base_name
echo "Where should the count start?"
read counter
echo "Whats the number of the last folder?"
read need
while [ $counter -le $need ]
do
	if [ $counter -le 9 ]
	then
		mkdir $base_name"0"$counter
	else
		mkdir "$base_name$counter"
	fi
	((++counter))
done
