#!/bin/bash
status=false
if [ ! $(env | grep -c -e "^MKDPP") -eq 0 ]
then
	status=true
fi
echo "environment variable found: $status"
if [ -f /usr/bin/mkdir++ ]
then
	echo "file found in binaries"
else
	echo "file not found in binares"
fi
echo "done"
