#!/bin/bash
status=false
if [ ! $(env | grep -c -e "^MKDPP") -eq 0 ]
then
	status=true
fi
echo "environment variable found: $status"
status=false
if [ -f /usr/bin/mkdir++ ]
then
	echo "file found in binaries: $status"
else
	status=false
	echo "file found in binaresi: $status"
fi
echo "script end"
